version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo-taxi"
    hostname: mongodb
    ports:
      - "27017:27017"
  application:
    image: taxi
    ports:
      - 8080:8080
    links:
      - mongo